import type { ReportSnapshot } from '../domain/report';
import { cn } from '../lib/utils';

function displayRange(range?: { low?: number; high?: number }) {
  if (!range) return '';
  if (range.low !== undefined && range.high !== undefined) return `${range.low}-${range.high}`;
  if (range.low !== undefined) return `>= ${range.low}`;
  if (range.high !== undefined) return `<= ${range.high}`;
  return '';
}

export function ReportPreview({ report, compact = false }: { report: ReportSnapshot; compact?: boolean }) {
  const rows = Object.entries(report.resolved_payload).filter(([, value]) => value.value !== undefined);
  const interpretation = Object.entries(report.resolved_payload).find(([key]) => key.startsWith('interpretation.'))?.[1];

  return (
    <article className={cn('report-paper', compact && 'report-paper-compact')} aria-label={`Report ${report.report_id} version ${report.version} preview`}>
      <header className="flex items-start justify-between gap-6 border-b-[3px] border-[#005fb8] pb-4">
        <div><div className="text-[21px] font-semibold leading-none text-[#004f91]">PathForge</div><div className="mt-1 text-[11px] text-[#5e5e5e]">Clinical Pathology Report</div></div>
        <div className="grid justify-items-end gap-0.5 text-right text-[10px] text-[#5e5e5e]"><strong className="font-semibold text-[#151515]">Report {report.report_id} / V{report.version}</strong><span>Issue {report.issue_number} / {report.issue_date}</span></div>
      </header>
      <section className="mt-7">
        <h2 className="mb-2 text-[11px] font-semibold uppercase tracking-[.08em] text-[#004f91]">Results</h2>
        <table className="w-full table-fixed border-collapse text-[9.5px]">
          <thead><tr className="bg-[#f2f4f6] text-left text-[8px] uppercase text-[#5e5e5e]"><th className="w-[34%] p-1.5">Test</th><th className="p-1.5">Result</th><th className="p-1.5">Unit</th><th className="p-1.5">Reference</th><th className="p-1.5">Flag</th></tr></thead>
          <tbody>{rows.map(([key, row]) => <tr key={key} className="border-b border-[#d9dde2]"><td className="p-1.5">{row.display}</td><td className="p-1.5">{row.value}</td><td className="p-1.5">{row.unit}</td><td className="p-1.5">{displayRange(row.reference_range)}</td><td className="p-1.5 font-semibold text-[#107c10]">{row.flag === 'normal' ? 'Normal' : row.flag}</td></tr>)}</tbody>
        </table>
      </section>
      {interpretation && <section className="mt-7"><h2 className="mb-2 text-[11px] font-semibold uppercase tracking-[.08em] text-[#004f91]">Interpretation</h2><div className="flex justify-between border-y border-[#d9dde2] p-2 text-[9.5px]"><span>Glucose interpretation</span><strong>{interpretation.display}</strong></div></section>}
      <footer className="mt-14 flex justify-between border-t border-[#d9dde2] pt-2 text-[8px] text-[#5e5e5e]"><span>Generated by PathForge</span><span>Page 1 of 1</span></footer>
    </article>
  );
}
