import { DatabaseBackup, FolderOpen, Save } from 'lucide-react';
import type { ReactNode } from 'react';

import { Button } from './ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';

export function Settings() {
  return <section className="page-grid"><header className="pane-titlebar"><div className="flex items-baseline gap-2"><h1>Settings</h1><span>Lab identity, operators, doctors, and backup</span></div><Button variant="default"><Save />Save changes</Button></header><Tabs className="settings-layout" defaultValue="lab"><TabsList className="settings-tabs"><TabsTrigger value="lab">Lab</TabsTrigger><TabsTrigger value="operators">Operators</TabsTrigger><TabsTrigger value="doctors">Doctors</TabsTrigger><TabsTrigger value="data">Data & backup</TabsTrigger></TabsList><TabsContent className="settings-content" value="lab"><SettingsGroup title="Lab identity"><div className="form-grid"><label className="form-field"><span>Lab name</span><input defaultValue="Sunrise Diagnostics" /></label><label className="form-field"><span>Phone</span><input defaultValue="+91 98765 43210" /></label><label className="form-field col-span-2"><span>Address</span><input defaultValue="12, Station Road, Kota, Rajasthan" /></label><label className="form-field"><span>Default signatory</span><select defaultValue="rao"><option value="rao">Dr. Kavita Rao, MD Pathology</option></select></label></div></SettingsGroup></TabsContent><TabsContent className="settings-content" value="operators"><SettingsTable columns={['Operator', 'Role', 'PIN', 'Status']} rows={[['Dr. Kavita Rao', 'Pathologist', 'Configured', 'Active'], ['Neha Singh', 'Technician', 'Configured', 'Active']]} /></TabsContent><TabsContent className="settings-content" value="doctors"><SettingsTable columns={['Doctor', 'Qualification', 'Registration', 'Use']} rows={[['Dr. Meera Iyer', 'MBBS, MD', 'RMC-11842', 'Referrer'], ['Dr. Kavita Rao', 'MD Pathology', 'RMC-09317', 'Signatory']]} /></TabsContent><TabsContent className="settings-content" value="data"><SettingsGroup title="Backup status"><div className="backup-row"><DatabaseBackup /><div><strong>Automatic local backup</strong><span>Last completed today at 08:00</span></div><Button>Run now</Button></div><div className="backup-row"><FolderOpen /><div><strong>External backup</strong><span>USB_BACKUP (E:) / Last completed 20 Feb 2026 at 18:42</span></div><Button variant="default">Export backup</Button></div></SettingsGroup></TabsContent></Tabs></section>;
}

function SettingsGroup({ title, children }: { title: string; children: ReactNode }) { return <section className="settings-group"><h2>{title}</h2>{children}</section>; }
function SettingsTable({ columns, rows }: { columns: string[]; rows: string[][] }) { return <table className="settings-table"><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row[0]}>{row.map(cell => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table>; }
